# Generated by Django 5.2.8 on 2025-12-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_corporate_id', models.CharField(max_length=100)),
                ('from_client_id', models.CharField(max_length=100)),
                ('to_corporate_id', models.CharField(max_length=100)),
                ('to_client_id', models.CharField(max_length=100)),
                ('transfer_type', models.CharField(max_length=50)),
                ('data_1', models.FileField(upload_to='uploads/')),
                ('data_2', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
