# Generated by Django 5.2.8 on 2025-12-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdata',
            name='data_1',
        ),
        migrations.RemoveField(
            model_name='transferdata',
            name='data_2',
        ),
        migrations.AddField(
            model_name='transferdata',
            name='data_1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdata',
            name='data_2_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
