# Generated by Django 5.2.8 on 2025-12-18 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_transferdata_data_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdata',
            name='data_1_url',
        ),
        migrations.RemoveField(
            model_name='transferdata',
            name='data_2_url',
        ),
        migrations.AddField(
            model_name='transferdata',
            name='data_1',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferdata',
            name='data_2',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
