# Generated by Django 5.2.8 on 2025-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_transferdata_data_1_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdata',
            name='data_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='data_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
