# Generated by Django 5.2.8 on 2025-12-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_transferdata_data_1_alter_transferdata_data_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdata',
            name='user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
