# Generated by Django 5.2.8 on 2025-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_transferdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdata',
            name='completed_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferdata',
            name='status',
            field=models.CharField(default='Uploaded', max_length=20),
        ),
    ]
